# Generated by Django 5.2.7 on 2025-10-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_make_slug_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
