# Generated by Django 5.2.7 on 2025-10-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_campania_created_at_alter_campania_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tmp_test_field',
            field=models.BooleanField(default=False),
        ),
    ]
