# Generated by Django 5.2.7 on 2025-10-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0001_initial'),
        ('condominio', '0002_rol_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='authz.rol'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
