# Generated by Django 5.2.7 on 2025-10-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_notificacion_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen representativa del servicio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en dólares del servicio', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicio',
            name='servicios_incluidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de servicios incluidos (ej: Guía, Transporte, Hotel)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='capacidad_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.usuario'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='punto_encuentro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
