# Generated by Django 5.2.7 on 2025-10-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_servicio_imagen_url_servicio_precio_usd_and_more'),
        ('condominio', '0005_usuario_documento_identidad_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
    ]
