# Generated by Django 5.2.7 on 2025-10-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_bitacora'),
        ('condominio', '0006_merge_20251010_2250'),
    ]

    operations = [
    ]
