# Generated by Django 5.2.7 on 2025-10-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_merge_0006_bitacora_0006_merge_20251010_2250'),
    ]

    operations = [
    ]
