# Generated by Django 5.2.7 on 2025-10-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0009_configuracionglobalreprogramacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del paquete turístico', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del paquete')),
                ('duracion', models.CharField(help_text='Duración total del paquete (ej: 3 días, 1 semana)', max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del paquete completo en USD', max_digits=10)),
                ('precio_bob', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en bolivianos (se calcula automáticamente)', max_digits=10, null=True)),
                ('cupos_disponibles', models.PositiveIntegerField(default=20, help_text='Número de cupos disponibles para este paquete')),
                ('cupos_ocupados', models.PositiveIntegerField(default=0, help_text='Número de cupos ya reservados')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de disponibilidad')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de disponibilidad')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Agotado', 'Agotado')], default='Activo', max_length=10)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar como paquete destacado')),
                ('imagen_principal', models.URLField(blank=True, help_text='URL de la imagen principal del paquete', max_length=500, null=True)),
                ('punto_salida', models.CharField(help_text='Punto de salida del paquete turístico', max_length=255)),
                ('incluye', models.JSONField(blank=True, default=list, help_text='Lista de lo que incluye el paquete (transporte, hotel, guía, etc.)')),
                ('no_incluye', models.JSONField(blank=True, default=list, help_text='Lista de lo que NO incluye el paquete')),
                ('campania', models.ForeignKey(blank=True, help_text='Campaña de descuento aplicable a este paquete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_con_descuento', to='condominio.campania')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'ordering': ['-destacado', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dia', models.PositiveIntegerField(help_text='Día del itinerario (1, 2, 3, etc.)')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden dentro del día')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio del servicio', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de finalización del servicio', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas específicas del servicio en este paquete', null=True)),
                ('punto_encuentro_override', models.CharField(blank=True, help_text='Punto de encuentro específico para este paquete (si difiere del servicio)', max_length=255, null=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.paquete')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.servicio')),
            ],
            options={
                'verbose_name': 'Servicio en Paquete',
                'verbose_name_plural': 'Servicios en Paquetes',
                'ordering': ['dia', 'orden'],
                'abstract': False,
                'unique_together': {('paquete', 'servicio', 'dia', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(help_text='Servicios/destinos incluidos en este paquete', related_name='paquetes', through='condominio.PaqueteServicio', to='condominio.servicio'),
        ),
    ]
